### ISSUE TITLE
Validate the `Ref` input for ostree based commits

### ISSUE THREAD

**Issue by gicmo** [osbuild/cockpit-composer#1011]
Not all values are accepted for the `Ref` field. If something wrong is put in there `osbuild` will fail very late in the build with something like:
```
error: Invalid refspec /rhel8/gateway
```
ostree uses a regex to validate the ref in [`ostree_parse_refspec`](https://github.com/ostreedev/ostree/blob/73742252e286e8b53677555dc1b0d52d55fb7012/src/libostree/ostree-core.c#L172):

```
#define OSTREE_REF_FRAGMENT_REGEXP "[\\w\\d][-._\\w\\d]*"
#define OSTREE_REF_REGEXP "(?:" OSTREE_REF_FRAGMENT_REGEXP "/)*" OSTREE_REF_FRAGMENT_REGEXP
#define OSTREE_REMOTE_NAME_REGEXP OSTREE_REF_FRAGMENT_REGEXP

g_regex_new ("^(" OSTREE_REMOTE_NAME_REGEXP ":)?(" OSTREE_REF_REGEXP ")$", 0, 0, NULL);
```

Discovered by @mrguitar

**Comment by bcl** [comment]
That should also be added to the compose API in osbuild-composer. I'm not sure it really belongs in the UI, but I'll leave that up to others to debate :)

**Comment by jkozol** [comment]
@bcl I think we should include this in the UI during the field entry so it is quicker to validate an incorrect ref. We want to display alert messages in the UI when an invalid ref is typed and not just on an attempted ostree build.
