### ISSUE TITLE
Lorax composer is sometimes installed instead of osbuild composer

### ISSUE THREAD

**Issue by jkozol** [osbuild/cockpit-composer#1040]
I have been unable to replicate this but sometimes lorax-composer can be installed instead of osbuild-composer.

**Comment by martinpitt** [comment]
This is also what happens in ELN right now: https://tiny.distro.builders/workload--sst_front_door-composer--fedora-empty-base--repository-fedora-eln--x86_64.html - there is no osbuild, but lorax-composer.

On Fedora 32 it's okay: https://tiny.distro.builders/workload--sst_front_door-composer--fedora-empty-base--repository-fedora-32--x86_64.html

**Comment by martinpitt** [comment]
In other words, why not make the preferred backend explicit? lorax-composer in RHEL 8.3 (or is that already osbuild as well?), and osbuild-composer on Fedora and RHEL ≥ 8.4?

**Comment by jkozol** [comment]
@martinpitt Thanks for the examples. I believed that we had already made the backend semi-explicit. Our spec file contains:

```
Requires:       weldr
Suggests:       osbuild-composer >= 14
```

I thought that this would always install osbuild-composer instead of lorax-composer but allow users to use lorax-composer if they want. Apparently it does not do this.
