### ISSUE TITLE
RHEL for Edge default Ref hint

### ISSUE THREAD

**Issue by gicmo** [osbuild/cockpit-composer#1065]
When no reference is specified in the UI `rhel/8/$ARCH/edge` will be used, it might be nice to hint at that value in the UI (input box?) so that it is clear to the user what happens if nothing is filled in there.

**Comment by teg** [comment]
Interesting. I thought about this too. On the one hand, that would be helpful, on the other, we create a tight coupling between the UI and the backend this way, so updating the backend might mean they get out of sync. An argument for why it might be ok not to have a hint would be that anyone who cares should fill it in, and the default is just so we don't have to fail.

We have a similar situation with other defaults like the image size, which I don't think we expose, and which differs between distros/image types.

A more involved solution would be to have an API to query these sorts of things.

**Comment by jkozol** [comment]
@teg I agree that it might be useful to get default values for the image customizations that can differ by type. Currently we call /compose/types to get a list of enabled image types. Perhaps we could expose more data for each of the types such as image size defaults and ostree defaults. I think it would also be nice to have the api pass strings for the image type label and the actual image type (i.e. amazon vs .raw).

**Comment by jkozol** [comment]
@gicmo Is there a default for fedora iot as well?

**Comment by teg** [comment]
> @teg I agree that it might be useful to get default values for the image customizations that can differ by type. Currently we call /compose/types to get a list of enabled image types. Perhaps we could expose more data for each of the types such as image size defaults and ostree defaults. I think it would also be nice to have the api pass strings for the image type label and the actual image type (i.e. amazon vs .raw).

This would make sense to me. Essentially all the info we pass in ImageOptions to Manifest might have defaults and might make sense to query.
