### ISSUE TITLE
Remove password verification

### ISSUE THREAD

**Issue by snoopy72** [osbuild/cockpit-composer#1079]
**Problem**

cockpit is blocking the usage of weak passwords. The system (Debian 10) is allowing this usage (checked with running "adduser" and the same weak password). Please add an option to disable your password verification

cockpit version 188
linux version: Debian GNU/Linux 10 (buster)

**Reproduce**

1. in the cockpit UI open "...:9090/users" and click "Add Account" (or whatever the original text is)
2. enter the username and a weak password (f.eg. "ma99" - of course twice)
3. click "create"

**Result**

You'll get the response "Password quality check failed: The password is shorter than 8 characters". 
Wrong: I never decided to have a minimal length for passwords.
For a locally driven (not connected) server it is rediculous to have long and complex passwords.

**System behaviour**

Using the bash on the system directly, there is no problem to create the user with the same password:

1. type "adduser testname"
2. type the weak password twice
3. confirm all other questions simply by pressing the "return" key
4. voila ! the user has been created without problems.

**Expected result**

The user should not be blocked when specifying a weak password. Please remove the password verification altogether ... or add an option in your software to avoid this behaviour.

(also requested in ticket #985 by jgiardino but closed without a real solution)

**Comment by marusak** [comment]
This belongs to https://github.com/cockpit-project/cockpit - I cannot transfer this issue for some reason, maybe I don't have enough privileges for this repo or github allows transferring only inside organization? @snoopy72 maybe you can transfer it there as author?

Back to the issue: Cockpit uses `pwscore` to check for password quality. 
```
$ /usr/bin/pwscore 
ma99
Password quality check failed:
 The password is shorter than 8 characters
```

This is configurable in `/etc/security/pwquality.conf`. (In this case `minlen=4` I guess?)

This however still leaves the question opened as if we should or should not enforce strong passwords if `useradd` does not enforce it either (I thought it does do that). Maybe a good approach would be to do something like anaconda does, that you need to click twice on `OK` if the password is weak to make sure you are aware you are using weak one.

**Comment by snoopy72** [comment]
Same problem in version 225.

The problem is not the warning itself - higer security is always welcome, because most users password ist "password" or "xxx". 

BUT:
Running a local (test) server for limited access and private LAN testing is something different. And even if somebody is thinking, strong password have to be forced ... when somebody wants a weak password, he/she should get it. It's not the job of a developer to teach the customer (i am a developer for 40+ years, so believe me).

The idea of @marusak (confirm the bad password) is a good way.

Reopening the case in "cockpit" with link to this case for these comments. Thanks, marusak.

**Comment by snoopy72** [comment]
Leading ticket should be in cockpit. closing this one.
