### ISSUE TITLE
German translation is confusing (honestly useless)

### ISSUE THREAD

**Issue by snoopy72** [osbuild/cockpit-composer#1080]
**Problem**

The german "translation" is a mess. Who ever translated that german texts should change the job. Seriously. 

Example 
Mounting a disk and define the folder (Storage > select disk > select content > filesystem > mount point)
  "Am Kofferraum montieren" (original: "Mount at boot")

Translated back the german text into english:
  "Fixing at the car luggage compartment"

Really ?

**Version**

current cockpit version

**Expected result**

remove the german "translation". it's not worth it and more confusing than helpful. Google translate is no help for complex languages like german.

**Comment by marusak** [comment]
This is provided by community and everyone is welcomed to participate: https://translate.fedoraproject.org/projects/cockpit-composer/master/
This funny German translations are most likely output from some not-so-very-useful machine translation that was tried some years ago - we saw similar strings in cockpit as well and people fixed them in the meantime.

**Comment by snoopy72** [comment]
Using the up-to-date version, those "funny translations" (there are NOT funny !) are still existing.

Due to the fact, that this project is "provided by community", those translations should be deleted immedeately - especially, when a native speaker points to those errors. We tried this software, because we are looking for small and easy to use software for our clients. A ridiculous and confusing "translation" (the are a lot of errors) is contraproductive and will (like in our case) push users and distributors like us far away. Inadequate reaction to those tickets are even worst. I always feel sad, when a good software idea is ruined by bad details and worse support.

Just my two cents.

**Comment by marusak** [comment]
Oh, this is against [cockpit](https://github.com/cockpit-project/cockpit) and not against cockpit-composer.
Anyway, it is fixed both in [weblate](https://translate.fedoraproject.org/translate/cockpit/master/de/?q=Mount+at+boot&sort_by=-priority%2Cposition&offset=3) and in [upstream](https://github.com/cockpit-project/cockpit/blob/master/po/de.po#L4595)

> Using the up-to-date version

Would you mind sharing what version is that? It was fixed in [this commit](https://github.com/cockpit-project/cockpit/commit/04db03fdff41c513dd05a897c572bff8f344924f#diff-5b78fe3b8a66eafe677903fefeaeb0ccR4023) from 17 July 2019 (should be in cockpit-199, now we are at 215).

**Comment by snoopy72** [comment]
cockpit version 188
linux version: Debian GNU/Linux 10 (buster)

(like in #1079)

I changed the language of course ... but i cannot recommend software with those technical problems to our clients. A lot of our clients (readers) dont have much IT skills and my job is, to check recommended software agaist those skills and the pracical usability. Recommending this version in the current state would damage my good reputation.

**Comment by snoopy72** [comment]
188 is the current version in debian buster .... those version, that the "normal" user will install.

**Comment by ondrejbudai** [comment]
Did you try using cockpit from backports repository? It has version 225, which should have this issue fixed.
