### ISSUE TITLE
Not all string are translatable

### ISSUE THREAD

**Issue by marusak** [osbuild/cockpit-composer#1084]
For example Czech is fully translated yet some strings in the UI are still in English. (the menu on the left)
```
 $ msgfmt --statistics po/cs.po
269 translated messages.
```
![untransl;atedmeno](https://user-images.githubusercontent.com/12330670/90487290-9016fd80-e13a-11ea-89a9-d6c2936c4e93.png)

Those strings are just not marked in the code as translatable, should be easy fix.

I quickly went through the plugin and this was the only place I could find. It might be worth though if someone from the team would also give this a try as I am not so familiar with the plugin to know all the places where I can get to.

**Comment by jgiardino** [comment]
I reviewed the UI for missing translations. These are strings that are not tagged for translation:
- In Create Image wizard
  - "Blueprint" (as shown in the example above)
  - All steps in the wizard navigation (as shown in the example above)
  - When RHEL for Edge is selected:
    "rhel/8/$ARCH/edge is the default, where $ARCH is determined by the host machine"
- In Edit Blueprint page > Available Components section > Pagination
  - "# per page" - It looks like the `titles` prop is where this string would be provided to the Pagination component.
  - Note that "#-# of #" is currently not translatable in the PF4 component.

**Comment by jkozol** [comment]
@jgiardino I am updating the translations per this issue. 

> When RHEL for Edge is selected:
"rhel/8/$ARCH/edge is the default, where $ARCH is determined by the host machine"

I believe this string is marked for translation but has not yet been translated.

**Comment by jkozol** [comment]
All possible strings are currently translated.
