### ISSUE TITLE
Edit Pakages, Create Image button size difference

### ISSUE THREAD

**Issue by gicmo** [osbuild/cockpit-composer#1158]
The `Edit Packages` and `Create Image` buttons are not the same size and look out of alignment therefore.

![button_alignments](https://user-images.githubusercontent.com/2040/98228095-6c549e00-1f58-11eb-8216-db6b5ab33673.png)

**Comment by KKoukiou** [comment]
That is because this project uses a mix of PF3 and PF4. These two buttons are actually one from the PF3 library, with CSS overrides to make it look like PF4 (apparently almost) and the other is indeed PF4.
