### ISSUE TITLE
Blueprint overview: No blueprints message not centred

### ISSUE THREAD

**Issue by gicmo** [osbuild/cockpit-composer#1159]
The helpful filler text is not centred, seems a bit off:

![3-blueprint-overview](https://user-images.githubusercontent.com/2040/98231152-56e17300-1f5c-11eb-9ccb-2216e954a68f.png)

Same is true when the blueprint is empty in the edit packages view (maybe on purpose here?):
![centering-2](https://user-images.githubusercontent.com/2040/98231345-99a34b00-1f5c-11eb-9eda-a40c398f5384.png)

**Comment by jgiardino** [comment]
Thanks for posting these, @gicmo! Which version of RHEL were you using?

**Comment by jkozol** [comment]
![errorrhel84](https://user-images.githubusercontent.com/11712857/99275158-72d1f800-282b-11eb-8aa5-60ef5eed3ddc.png)

**Comment by jkozol** [comment]
This was on rhel 8.4 nightly

**Comment by gicmo** [comment]
> Thanks for posting these, @gicmo! Which version of RHEL were you using?

cockpit-composer was running on RHEL 8.3.0, I guess more important the version was `cockpit-composer-22.1-1.el8.noarch`. Hope that helps ;)

**Comment by KKoukiou** [comment]
This also exists on master, and it's because of using PF4 - PF3 mixed. In this case you are using the empty state component from PF4, together with a button from PF3 (with cockpit's overrides which make it look like PF4.

So in cockpit, we are mostly PF4 only, so the CSS overrides file which you use for making PF3 look like PF4, might not be up to date with FP4  or might not work well with new components that PF4 offers. Because we don't update it anymore.

**Comment by jkozol** [comment]
Thanks to the updates to @patternfly/react-core this issue has been fixed for me. It seems that this was an issue when we were using version 4.32.1. @patternfly/react-core was updated from this version in cockpit-composer release 24. The most recent RHEL release was 22.1 so this alignment issue should be fixed next time we release to RHEL.

@KKoukiou I am unable to replicate this on master. Can you provide steps to replicate this?

**Comment by KKoukiou** [comment]
> Thanks to the updates to @patternfly/react-core this issue has been fixed for me. It seems that this was an issue when we were using version 4.32.1. @patternfly/react-core was updated from this version in cockpit-composer release 24. The most recent RHEL release was 22.1 so this alignment issue should be fixed next time we release to RHEL.
> 
> @KKoukiou I am unable to replicate this on master. Can you provide steps to replicate this?

I confirm that the empty state is indeed centered on master.

**Comment by jkozol** [comment]
Thanks!
