### ISSUE TITLE
Translation missing in export modal

### ISSUE THREAD

**Issue by jkozol** [osbuild/cockpit-composer#1192]
In the export modal the word "Text" is not translated.

![rhel84Translation](https://user-images.githubusercontent.com/11712857/101843720-d09aec80-3b18-11eb-8833-ef523f49f18a.png)

**Comment by marusak** [comment]
Czech translation of `text` is `text` :) Checked in other languages and it seems it is very similar to `text` often:
```
po/cs.po:msgid "Text"
po/cs.po-msgstr "Text"
--
po/es.po:msgid "Text"
po/es.po-msgstr "Texto"
--
po/fr.po:msgid "Text"
po/fr.po-msgstr "Texte"
--
po/pt_BR.po:msgid "Text"
po/pt_BR.po-msgstr "Texto"

po/ru.po:msgid "Text"
po/ru.po-msgstr "Текст"

po/uk.po:msgid "Text"
po/uk.po-msgstr "Текст"
```

Just no noticed, that slovak is not present anymore. I though I kept it updated, but seems it slipped through. 55ee2e5d

**Comment by jkozol** [comment]
Ahaha I guess I should have translated it myself. Thanks.
