### ISSUE TITLE
Build same Blueprint using different Sources

### ISSUE THREAD

**Issue by bstin** [osbuild/cockpit-composer#1231]
### Description of problem
This is not a problem its a question that I can't find in the weld / lorax / osbuild documentation....

How do I build the same blueprint using different sources? For example, I have both F32 and F33 sources, but I can't figure out how to constrain a build to only use F32 packages. 

Is there something I'm missing?

**Comment by larskarlitski** [comment]
Hey @bstin. Sources are global for all blueprints and are added in addition to the system's repositories.

Image Builder does not support building images for operating systems that are different from the host yet. But that's on our roadmap.
