### ISSUE TITLE
[test] Image creation is failing on rhel-9

### ISSUE THREAD

**Issue by marusak** [osbuild/cockpit-composer#1391]
CI is busted on rhel-9.
See for example [here](https://logs.cockpit-project.org/logs/pull-2831-20220121-131415-44b03dd0-rhel-9-0-osbuild-cockpit-composer/log.html).
It fails 100% of time on rhel-9 always like this:
![TestImage-testCancel-rhel-9-0-127 0 0 2-2201-FAIL](https://user-images.githubusercontent.com/12330670/150538298-08c33993-a23c-481c-8bf4-6313a2c44b68.png)

It is happening already for at least 24 days, possibly longer (I just saw one PR that was 24 days old and already affected).

**Comment by martinpitt** [comment]
See also https://github.com/osbuild/cockpit-composer/pull/1385#issuecomment-1003884825

**Comment by martinpitt** [comment]
This has been broken for over a month now, and c-composer is also not even tested on fedora-35. I sent https://github.com/cockpit-project/bots/pull/2872 to disable the automatic test and move it to manual. Let's move it back once it's fixed.

**Comment by martinpitt** [comment]
Thanks @jkozol ! That'd be appreciated -- the RHEL 9 gating test has failed for a while, and so far we've waived it. But that risks breaking it further.

**Comment by jkozol** [comment]
Fixed by #1394

**Comment by jkozol** [comment]
@martinpitt Figured I would post here. There has now been a RHEL 9 release with fixed tests. Expect it in the next nightly.
