### ISSUE TITLE
Untranslated table headings

### ISSUE THREAD

**Issue by marusak** [osbuild/cockpit-composer#1419]
![unnamed](https://user-images.githubusercontent.com/12330670/166643554-28b78db3-e9b3-472f-852a-bdbda76d9e46.png)

I believe that it is not enough to just enumerate them, they need to be marked as translatable strings:
```
pages/blueprint/index.js:                            cells={["Full name", "User name", "Server administrator", "Password", "SSH key", "Actions"]}
```

**Comment by jkozol** [comment]
The UI for this has changed enough for this to no longer be relavent. Overall, will be verifying table headings more in the newer UI. Thanks!
