### ISSUE TITLE
Start osbuild-composer button is shown when user has no permissions to start

### ISSUE THREAD

**Issue by jelly** [osbuild/cockpit-composer#1425]
### Description of problem

If you prepare an VM and login as admin you are shown a start service button but lack permissions to do so.

### Component (web, API, etc)

web

### Version or commit hash (if applicable)

9ba8ddbe89dc5429f7a1a75af4c73e835c30b5b9

### How often reproducible

Always

### Steps to Reproduce

1. Login as admin
2. Click on start osbuild-composer service

### Actual results

```
The service osbuild-composer was not started. Message: Not permitted to perform this action.
```

### Expected results

Do not show the button when you have no permissions to start it.

**Comment by jkozol** [comment]
Closed in favor of #1754
