### ISSUE TITLE
Unification: Packages and modules

### ISSUE THREAD

**Issue by lucasgarfield** [osbuild/cockpit-composer#1463]
Blueprints support both `[[Packages]]` and `[[Modules]]`. However, there are currently no differences in how they are treated by `osbuild-composer`, both are treated as rpm package dependencies.

Keeping track of whether a package in a blueprint has been entered under the `[[Packages]]` or `[[Modules]]` section introduces additional complexity for no benefit. 

Therefore, #1461 takes a bold step: all modules are converted into packages in the blueprint workspace and therefore in the blueprint upon commit. 

However, we still need to reach a formal consensus on whether this is whether this behavior is really what we want or not. Let's use this issue to discuss further.

**Comment by teg** [comment]
There is no way to enter modules in the UI, right? So this would be if someone pushes a blueprint manually and then loads it in the UI and saves it again?

In this case we hide but preserve any other options we don't know, right?

**Comment by lucasgarfield** [comment]
That's correct, the UI does not distinguish between packages and modules (both are shown in the list of packages, we `concat()` any modules onto the list of packages) and there is no way to enter a module. 

The 'conversion' from a module to a package would occur if someone created an image (or in the future updated the blueprint, feature is yet to be implemented) after loading a blueprint containing `[[Modules]]`. Creating the image/updating the blueprint also bumps the version by +0.0.1.

Hidden blueprint options are preserved, yes. But I would argue `[[Modules]]` shouldn't be considered hidden as they appear in the package list.

**Comment by teg** [comment]
My concern about this would be that once we (finally!) add modules support, this might become confusing. I would have much preferred if modules were not there until implemented fully, or that they would be ignored completely in cockpit-composer as they cannot be edited, but as they currently are, the situation is weird.

Imagine a future when weldr treats `Packages` and `Modules` differently, if you use the feature on the command line, it would work, but if you load and save it in cockpit composer you'd break it, even if you were editing the blueprint for other reasons not touching packages / modules at all.

**Comment by lucasgarfield** [comment]
I'm fine with completely ignoring modules. I didn't know we could do that! @jkozol?

**Comment by jkozol** [comment]
I think that ignoring modules should work. In the packages PR you could just work with `Packages` and when we do the store rewrite we ignore `Modules` **_but_** keep in mind that they will be added at some point.

**Comment by teg** [comment]
Sorry, I was unclear. I wish we had ignored them from the beginning. Could we start ignoring them after the rewrite? Possibly, but worth a discussion, I didn't mean to tell you to do it ;)

Possibilities:

Merge as you do here - makes it simple, but changes what is in the store without the user realising

Present packages and modules as one thing, but keep the distinction internally, i.e. status quo - forward compatible, but won't the behavior be weird? what's the result of removing and adding again a module from the ui? surely it now has turned into a package?

Hide modules as all other unsupported features - seems the cleanest, but would need to make sure backwards compatibility is communicated and documented, and we should think about if there are valid uses of the current behavior.

**Comment by lucasgarfield** [comment]
Support for modules has been removed in 403a0d.
