### ISSUE TITLE
call depsolve api when modifying recipe

### ISSUE THREAD

**Issue by jgiardino** [osbuild/cockpit-composer#158]
### Description of problem
When adding/removing components in a recipe, the list of dependencies should be updated to reflect the change in components.

### Component (web, API, etc)
web

### How often reproducible
always

### Steps to Reproduce

Steps below are based on the updates made in #157 where a number of components is included in 
the tab labels for "Selected Components" and "Dependencies".
1. Create a new recipe
2. Add a component. The number of dependencies displaying in the "Dependencies" tab will change. 
3. Add another component. The number of dependencies increases
4. Click Save, then refresh the page. the number of dependencies listed in the tab will change

### Actual results
The number of dependencies changes between steps 3 and 4 because different api calls and methods are being used between adding components and loading the recipe on refresh.

In step 3, the list of dependencies per component is being combined to form the list of dependencies for the recipe. This list and number of items currently comes from the api call `/api/v0/modules/info/<modules>` being made at steps 2 and 3.

### Expected results

After adding or removing a component, the list of dependencies for a recipe should instead be generated by an api call that takes all selected components in a recipe. I think the correct api call in this case is `/api/v0/projects/depsolve/<projects>` with `<projects>` being a list of all selected components in the recipe.

### Additional info
* When viewing the component details, we make api calls to get the full set of metadata, list of dependencies, and list of builds (i.e. version-release options available for the component). For retrieving the list of dependencies for a component, I'm not sure if `/api/v0/modules/info/<modules>` is the right api call, or if we should use `/api/v0/projects/depsolve/<projects>` instead. The latter provides just a list of dependencies. The former provides a list of dependencies and additional metadata, but the same metadata is also returned with `/api/v0/projects/info/<projects>` which is the api call we use to get the list of builds available for a component.
* Save currently reloads the contents of the recipe to ensure that what displays in the UI matches what's saved to the backend, but in this case the dependencies are not being passed from the api call to the UI.

**Comment by jkozol** [comment]
I can't reproduce this issue.
