### ISSUE TITLE
Still using codecov?

### ISSUE THREAD

**Issue by martinpitt** [osbuild/cockpit-composer#1631]
While reviewing our current Cockpit CI secrets, I found [this gem](https://github.com/osbuild/cockpit-composer/blob/f37780daf8cc19cc7dedb5baed2dfcf1f3df0dc8/test/run#L20) in test/run:

```
if [ -f ~/.config/codecov-token ]; then
  token=$(cat ~/.config/codecov-token | sed 's/\n//g')
  curl --silent localhost:8080/foo.sh | CODECOV_TOKEN=$token bash
fi
```

This is not going to do anything useful, localhost:8080 is not a thing. This was done two years ago by @larskarlitski  in commit cb77a60c289bc1, before it was doing `curl -s https://codecov.io/bash | bash` which looks more functional (but of course scary!)

@jkozol , @larskarlitski Do you still use/need this? Or can this shell bit disappear, and we drop the code coverage token from our secrets?

**Comment by larskarlitski** [comment]
I don't remember doing this, and definitely don't need it anymore.

Thanks for asking!

**Comment by martinpitt** [comment]
Danke! I removed it from our secrets repo, and sent https://github.com/cockpit-project/cockpituous/pull/536 to clean up the last vestige of that. If you want to bring this back, please use a GitHub workflow and a project GitHub secret.
