### ISSUE TITLE
Add more information and columns for the blueprint table

### ISSUE THREAD

**Issue by jkozol** [osbuild/cockpit-composer#1686]

**Comment by jkozol** [comment]
Sorry this isn't clear. The space that needs to be addressed isn't the amount of vertical space but the lack of information and amount of horizontal space:

![Screenshot from 2023-01-30 14-43-27](https://user-images.githubusercontent.com/11712857/215494866-c7c9b0c2-c9c0-4fc8-88c7-7e2a3e2cd938.jpg)

**Comment by regexowl** [comment]
Ah, got it. So what should the final result look like? Do we want to add some columns or "shrink" the table?

**Comment by jkozol** [comment]
I'm thinking add columns but unsure what to display. Maybe last image build, number of images built, number of customizations. Idk exactly. What do you think?

**Comment by jkozol** [comment]
To start we can add `Date of last image creation`, `number of images built`, `number of selected packages`.

Eventually add `blueprint version`.
