### ISSUE TITLE
Incorrect header for Filesystem modal

### ISSUE THREAD

**Issue by kingsleyzissou** [osbuild/cockpit-composer#1899]
The header says `firewall` and not `filesystem` 

![image](https://github.com/osbuild/cockpit-composer/assets/20438192/3fd1c3bb-7eb6-4ebd-baa1-b189fe032be5)

**Comment by ochosi** [comment]
Oh, I thought I fixed this, too...
https://github.com/osbuild/cockpit-composer/pull/1871

**Comment by kingsleyzissou** [comment]
Missed this! I took this from Terry's demo... maybe he's using an older version of cockpit-composer
