### ISSUE TITLE
Translations locked due to merge conflict

### ISSUE THREAD

**Issue by rffontenelle** [osbuild/cockpit-composer#2031]
According to [alert on Weblate](https://translate.fedoraproject.org/projects/cockpit-composer/main/#alerts):

> **Could not merge the repository.**
> 
> Weblate could not merge upstream changes while updating the repository.
> 
>     Rebasing (1/1)
>     Auto-merging translations/tr.json
>     CONFLICT (content): Merge conflict in translations/tr.json
>     error: could not apply c61d6ad8... Translations from Weblate
>     hint: Resolve all conflicts manually, mark them as resolved with
>     hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
>     hint: You can instead skip this commit: run "git rebase --skip".
>     hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
>     Could not apply c61d6ad8... Translations from Weblate
>      (1)
> 
> **Typical workflow for fixing merge conflicts**
> 
> 1. Open an existing checkout of the upstream repository or perform a fresh one.
> 2. Commit all pending changes in Weblate and lock the translation component. <br>`wlc commit; wlc lock`
> 3. Add Weblate exported repository as a remote.<br>`git remote add weblate https://translate.fedoraproject.org/git/cockpit-composer/main/ ; git remote update weblate`
> 4. Merge Weblate changes and resolve any conflicts.<br> `git merge weblate/main`
> 5. Rebase Weblate changes on top of upstream and resolve any conflicts.<br>`git rebase origin/main`
> 6. Push changes into upstream repository.<br>`git push origin main`
> 7. Weblate should now be able to see updated repository and you can unlock it.<br>`wlc pull ; wlc unlock`
> 
> [Check the FAQ for info on how to resolve this.](https://docs.weblate.org/en/weblate-5.6.2/faq.html#merge)
>
> Appeared 5 months ago, last seen 27 seconds ago

**Comment by kingsleyzissou** [comment]
@croissanne I've followed the steps here to get this going again and fixed the conflicts, but I don't have permissions to run the `wlc unlock` command this, do you?

**Comment by rffontenelle** [comment]
I have and it is now unlocked. Solved the conflict, I simply requested pulling commits from this upstream repository, and Weblate unlocked it
