### ISSUE TITLE
no edge ami and edge vsphere image type found in web ui

### ISSUE THREAD

**Issue by yih-redhat** [osbuild/cockpit-composer#2039]
Description:
no edge ami and edge vsphere image type found in web ui, they are supposed to be there as https://github.com/osbuild/cockpit-composer/pull/2027 is already merged two weeks ago.

Reproduce steps:
1. Get rpm package from https://copr.fedorainfracloud.org/coprs/g/osbuild/cockpit-composer/build/7907597/
2. Install cockpit-composer and login web UI.
3. Create a blueprint and then create image.
4. Cannot find edge ami and edge vsphere image in the list, please see screenshot.

![image](https://github.com/user-attachments/assets/64e0e572-c6fb-438b-abe8-0b7999a4e4d4)

**Comment by croissanne** [comment]
@yih-redhat that copr tracks the latest preview release (so that would still be 50 at he time of testing, though 52 by now). We created the @osbuild/cockpit-composer-main  copr which is the latest main build. This should be fixed by now.

**Comment by kingsleyzissou** [comment]
This should be fixed now
