### ISSUE TITLE
Refactor available components

### ISSUE THREAD

**Issue by jgiardino** [osbuild/cockpit-composer#249]
The Available Components displays in the Edit Blueprint page, and currently includes the following features:

1. Ability to filter components by name (this is handled by an api call, given the number of components available in a source)
2. Ability to page through the components (also handled by an api call)

Currently, the following issues exist with this panel:

1. If an error occurs fetching available components, no indication is given in the UI. An error state message should display, similar to what was added for Blueprints and Blueprint Components in #268
    - Additionally, it would be helpful to provide suggestions on how to resolve the error. For example, I see this issue when I'm not connected to VPN, and therefore my repos can't sync. For that case, telling the user to check that their repos can sync and providing an action in the UI to restart lorax-composer would be helpful.
2. When a filter is entered that returns no results, no indication is given in the UI. An empty state message, similar to the ones that display for other filterable contents, should display instead.
3. A loading message was added in #248, but it should be updated to display anytime contents are being fetched. Currently, it only displays when fetching the 1st page of unfiltered contents, but not when navigating to pages and not when filtering contents.
    - When the user filters the contents, should we always maintain the 1st page of non-filtered contents in the store? This way when the filter is cleared, there isn't a need to fetch the first page again, and it can load immediately.
4. When a filter is entered that includes a space or comma-separated values, the UI should handle these separate values in the api call.
    - For example, "emacs,vim" will currently get submitted as `/api/v0/modules/list/*emacs,vim*?limit=50&offset=0` which will return only packages that end with "emacs" or start with "vim". But instead, the call should be `/api/v0/modules/list/*emacs*,*vim*?...`
    - The following filter values specified by the user should return the same results:
      - "x, y"
      - "x,y"
      - "x y"
5. When a filter is entered, the results should be sorted so that all the results that start with the value are first, followed by all results that do not start with the value. 
    - NOTE: this might require an update to the api itself.

**Comment by jgiardino** [comment]
#276 should be reviewed as part of this issue

**Comment by jkozol** [comment]
Only issue 4 still remains so that issue has been moved to #1026. This issue can be closed.
