### ISSUE TITLE
Component version is always the same

### ISSUE THREAD

**Issue by andreasn** [osbuild/cockpit-composer#260]
### Description of problem
Not sure if this is a real issue, maybe it's only my setup.
If I press a component in the **Edit Blueprint** > **Available Components** list, and try to select something else in the **Version Release** dropdown, I only ever get one version.

![screenshot from 2018-06-28 14-59-19](https://user-images.githubusercontent.com/209895/42036002-8cc1022a-7ae4-11e8-9151-296e46bf0dbb.png)

### Component (web, API, etc)
Web

### Version or commit hash (if applicable)
0.1.0

### How often reproducible
Always

### Steps to Reproduce

1. Click **Edit Blueprint**
2. Select a component in the **Available Components** list
3. Try to change **Version Release**

### Actual results

Can't change version release

### Expected results

Either for it to not display a dropdown (because there is nothing else to select), or for more versions to show up in the dropdown.

**Comment by jgiardino** [comment]
I'd like to be able to test this UI against a dataset that has multiple versions available for a component. 

@andreasn @larskarlitski  Do you have any suggestions on how to get a dataset I can use? 

My assumption is that the user could have a mix of components, where some have several options and some have only one. For that scenario, and in the case where only one option is available, do you think displaying the value as read-only is the right thing to do? I question if that's more confusing than a select menu with just one option, but we can also always do user testing to confirm.

**Comment by KKoukiou** [comment]
This is indeed reproducible.

For example on my system I have libvirt package provided by two different repositories, and the versions in these are different. See bellow:
```
# dnf list libvirt 
Last metadata expiration check: 0:05:28 ago on Thu 25 Apr 2019 03:05:08 PM CEST.
Installed Packages
libvirt.x86_64                                                         5.1.0-4.fc30                                                          @updates-testing                
Available Packages
libvirt.src                                                            5.2.0-2.fc30                                                          group_virtmaint-sig-virt-preview
libvirt.x86_64                                                         5.2.0-2.fc30                                                          group_virtmaint-sig-virt-preview
```

However lorax allow me to install only 5.2.0?
![libvirt-version-available](https://user-images.githubusercontent.com/14921356/56738334-b1492300-676c-11e9-9f2a-80ef86ec3d9b.png)

I didn't looks at the code yet, but from user perspective, is that expected? @larskarlitski

**Comment by jkozol** [comment]
Closed as out of date
