### ISSUE TITLE
Image doesn't go away if I stop a build from the CLI

### ISSUE THREAD

**Issue by andreasn** [osbuild/cockpit-composer#278]
### Description of problem
I stopped a build from the CLI, but it doesn't reflect in the UI

### Component (web, API, etc)
web

### Version or commit hash (if applicable)
0.1.0

### How often reproducible
Always

### Steps to Reproduce

1. hit Create Image and start a build in the web UI
2. Go to the CLI and cancel the build
3. Check the status in the web UI

### Actual results
The build is still visible in the web UI

### Expected results
That it should go away if I remove it from the CLI

### Additional info
![screenshot from 2018-07-05 13-56-44](https://user-images.githubusercontent.com/209895/42322133-964e03e8-805b-11e8-91c1-14984c2102d2.png)

**Comment by KKoukiou** [comment]
@larskarlitski correct me if I am wrong, but we don't get event's from the lorax API. So this is not possible till we have events.
In these case, I suggest to close all issues that require events, and have a single one for the RFE to use events from the API once they are available.

**Comment by larskarlitski** [comment]
> @larskarlitski correct me if I am wrong, but we don't get event's from the lorax API. So this is not possible till we have events.

Indeed. An alternative is to poll the API, but I don't think that's a good idea.

> In these case, I suggest to close all issues that require events, and have a single one for the RFE to use events from the API once they are available.

Agreed. Please link back to the individual ones though if you do that. Thanks!

**Comment by jkozol** [comment]
We currently poll the api to get compose status. The UI reflects the canceled compose on the next status check.
