### ISSUE TITLE
URL that doesn't exist displays blank page

### ISSUE THREAD

**Issue by jgiardino** [osbuild/cockpit-composer#288]
### Description of problem
If you navigate to a url that doesn't exist, a blank page will display

### Component (web, API, etc)
web

### Version or commit hash (if applicable)
0.1.0

### How often reproducible
always

### Steps to Reproduce

1. Specify a url that doesn't exists, like `/welder#/nope`

### Actual results
A blank page displays

### Expected results
Some type of 404 message

**Comment by jgiardino** [comment]
@andreasn or @larskarlitski 
Could you include a link or example of how you handle this in cockpit?

**Comment by andreasn** [comment]
![screenshot from 2018-07-10 18-00-00](https://user-images.githubusercontent.com/209895/42522318-1869241c-846b-11e8-82ed-6d0bc080309e.png)

**Comment by jkozol** [comment]
There is a Not Found message and icon when an unknown page is loaded now.
