### ISSUE TITLE
Create Image notification messages should be updated

### ISSUE THREAD

**Issue by jgiardino** [osbuild/cockpit-composer#289]
### Description of problem
The notification messages that display as part of the Create Image workflow should be updated to match the messages defined in the [design document](https://docs.google.com/document/d/1O5AoTYWAoS0oyGHPofew5n3f29O90XgKp092n5eN6xY/edit?usp=sharing)

### Component (web, API, etc)
web

### Version or commit hash (if applicable)
0.1.0

### How often reproducible
Always

### Additional info
Refer to the Toast Notifications section in the [design document](https://docs.google.com/document/d/1O5AoTYWAoS0oyGHPofew5n3f29O90XgKp092n5eN6xY/edit?usp=sharing) for more details.

**Comment by jgiardino** [comment]
Marking this as priority 1 to capture the work for removing the current notifications.
The remaining work might be priority 2 or postMVP.

**Comment by KKoukiou** [comment]
@jgiardino this looks like its solved already?
I was checking the code here, and the messages match your descriptions. https://github.com/weldr/welder-web/blob/master/data/NotificationsApi.js#L32..L110

**Comment by jkozol** [comment]
@jgiardino This issue seems mostly resolved. Everything in the design document is either implemented or outdated except for the toast notifications. Do we still want toast notifications for every image completion or failure?
