### ISSUE TITLE
Blueprints list loading state

### ISSUE THREAD

**Issue by jgiardino** [osbuild/cockpit-composer#305]
### Description of problem
Currently, the app state gets updated with `fetchingBlueprints: false` when the action FETCHING_BLUEPRINT_NAMES_SUCCEEDED is called. However, the contents needed to populate the page aren't actually added at this time. Now that the ability to pull the list of images is included in PR #304, it's much more obvious that this is the case.  

Instead, the state should be updated when the image contents are successfully fetched (e.g. FETCHING_BLUEPRINTS_SUCCEEDED).

**Comment by jkozol** [comment]
This is outdated.
