### ISSUE TITLE
does not warn about depsolv errors

### ISSUE THREAD

**Issue by andreasn** [osbuild/cockpit-composer#308]
### Description of problem
I tried to build a tar of a blueprint I created about a week ago. It contained Cockpit and it's dependencies. At the time, cockpit version 171 was the latest version, but since then cockpit 172 was released (and now cockpit-171 is no longer in that repo apparently). When I pressed **Create** in the dialog nothing happened. I then tried to build it from the CLI with composer-cli instead, and it gave me this error:
`2018-07-19 12:21:09,518: Problem depsolving tester: The following package(s) had problems: cockpit-171 (No package(s) available to install)`

I would have expected to see that error in the web UI.

**Comment by jkozol** [comment]
I was unable to replicate
