### ISSUE TITLE
refactor api calls for Blueprint page

### ISSUE THREAD

**Issue by jgiardino** [osbuild/cockpit-composer#323]
The Blueprint page should load immediately, and not make api calls for depsolve or composes until requested by the user.

- When the user navigates to the Blueprint page and the Details tab loads, don't make any api calls for composes or dependencies
- When the user clicks the primary tab labeled "Selected Components":
  - Then the depsolve api call is called 
  - The loading icon displays in the Dependencies tab until the components are loaded. When the Dependencies are returned, the badge with number of dependencies will display with the tab
  - The loading icon will display on the secondary "Selected Components" tab
- When the user clicks the primary tab labeled "Images":
  - The composes api call is called
  - The loading icon displays in the page
- After fetch is complete for any of the cases listed above, if an error occurred, then an error message should display (similar to the one added for Blueprints in #268)

**Comment by jkozol** [comment]
moved to #940
