### ISSUE TITLE
Refactor end-to-end tests

### ISSUE THREAD

**Issue by jgiardino** [osbuild/cockpit-composer#324]
Currently the selectors used to identify the UI elements for end-to-end tests are flimsy, and easily broken when UI updates are made.

Instead, any element that is targeted in an end-to-end test should have an html `id` attribute assigned which can be used to identify the element in the test.

**Comment by jgiardino** [comment]
Currently, these tests cannot be tested with a local build.

**Comment by jgiardino** [comment]
@xiaofeng, can you provide comments on the suggestions in this issue. You mentioned during standup that the latest version of firefox doesn't support using the `id` attribute as a selector. Is that in the context of tests? or just in general (tests and css)?

**Comment by jgiardino** [comment]
@xiaofeng, are these instructions still valid for running end-to-end tests: https://github.com/weldr/welder-web/blob/master/test/end-to-end/README.md

**Comment by henrywang** [comment]
Just run ```make lorax-test```.
The [PR357](https://github.com/weldr/welder-web/pull/357) changes a lot of things. But for now, ```make lorax-test``` works for you.

**Comment by henrywang** [comment]
Here's a detailed description about locating element by id - https://github.com/webdriverio/webdriverio/issues/2392
That means ```#id``` will not be supported by geckodriver. But ```body #id``` still works.

No better way to locate element then by id. The best id attribute should be unique and meaningful.

The unique means every id in html should have unique name. That'll be easy to locate element when write UI automation test and easy to work with automation code.

The meaningful means the id name should represent which content this id identifies. Reading react and automation code becomes easy if id is meaningful. e.g. In the edit blueprint page, each available or selected component should have id attribute with a meaningful name, like ```[data-component="bash"]```.

**Comment by larskarlitski** [comment]
Not sure if that's what you're suggesting @henrywang, but I've used `data` attributes instead of ids before and that worked quite nicely. For example in https://github.com/weldr/welder-web/commit/0be7c1c89a71a1e69c86c775920c5cbc72497e64

**Comment by henrywang** [comment]
@larskarlitski, I found your change. This change saves at least 6 lines of code and make test code easy to understand. From my perspective, both `id` and `data` are OK for me. But after some research, I think `data-*` is more reasonable for this use case.
The definition and usage of `id`:

> The id attribute specifies a unique id for an HTML element (the value must be unique within the HTML document).
The id attribute is most used to point to a style in a style sheet, and by JavaScript (via the HTML DOM) to manipulate the element with the specific id.

The definition and usage of `data-*`:

> The data-* attributes is used to store custom data private to the page or application.
The data-* attributes gives us the ability to embed custom data attributes on all HTML elements.
The stored (custom) data can then be used in the page's JavaScript to create a more engaging user experience (without any Ajax calls or server-side database queries).
The data-* attributes consist of two parts:
The attribute name should not contain any uppercase letters, and must be at least one character long after the prefix "data-".
The attribute value can be any string.
Note: Custom attributes prefixed with "data-" will be completely ignored by the user agent.

@jgiardino, I prefer `data-*`.

**Comment by martinpitt** [comment]
> The id attribute is most used to point to a style in a style sheet,

Just for the record. This [really should not be done](https://css-tricks.com/specifics-on-css-specificity/). CSS should be specified in terms of classes, not IDs.

Not related to this PR of course, just spreading the word :)

**Comment by jgiardino** [comment]
Hi @sfondell, we were just chatting about this at standup. I'll try to summarize what I think we all agreed to, but anyone please suggest otherwise if I didn't capture this correctly. Here are recommendations on how to move forward with this:

- For any html element that you need to add an identifier attribute to, use a `data-` attribute instead of `id`.
  - If an element already has an `id` attribute, please keep it both in the UI component and the test. It's probably there for a reason.
  - `data-` attributes can be whatever you want. I was thinking we would just use `data-id` and set the value to something that's still relatively unique (i.e. unique relative to it's parent), like `data-id="cmpsr-modal-footer"`.
- @martinpitt's recommendation was to opt for simplicity. Specifically, we don't want to add `data-id` attributes to every element we target in a test, but we don't want to have overly complex selectors like [this one](https://github.com/weldr/welder-web/blob/master/test/end-to-end/pages/createImage.js#L26) `label[for="textInput-modal-markup"] + div select'. I think to put this into some type of guideline you can follow, I'd suggest this:
  - Identify selectors that seem overly complex. Selectors with a lot of space combinators (e.g. `div select`), element type selectors (e.g. `div` or `select`) or any sibling combinator (e.g. `+`) could be things to look for replacing. 
  - Selectors based on classes are probably ok, especially if they're specific like [this example](https://github.com/weldr/welder-web/blob/master/test/end-to-end/pages/createImage.js#L30) `${this.dialogRootElement} .modal-footer .btn-primary`. In this case, there's only going to be one modal footer, and one primary button in that footer. 
  - But classes that might be used often are questionable, like [this one](https://github.com/weldr/welder-web/blob/master/test/end-to-end/pages/createImage.js#L23) `${this.dialogRootElement} p[class="form-control-static"]`, because it's always possible that additional elements could be added that use the same class. 


Please let me know if you need any further clarification on this. And feel free to try something out and push it up to get feedback, too.

**Comment by jkozol** [comment]
The tests have mostly been rewritten.
