### ISSUE TITLE
Tabs with pf styles

### ISSUE THREAD

**Issue by jgiardino** [osbuild/cockpit-composer#349]
After addressing issue #247, additional updates are needed to apply the [patternfly style](https://rawgit.com/patternfly/patternfly-react/gh-pages/index.html?knob-Tab%201%20Tittle=Tab%201&knob-Tab%202%20Tittle=Tab%202&knob-Tab%203%20Tittle=Tab%203&selectedKind=patternfly-react%2FWidgets%2FTabs&selectedStory=Basic%20Tabs%20-%20PF%20style&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs) to the tabs listed below:

  - **Blueprint contents**, components/ListView/BlueprintContents.js
    - This UI displays in two places:
      - On Blueprint page, click Selected Components tab. This tab has a second set of tabs as shown below:
        ![image](https://user-images.githubusercontent.com/21063328/42388316-2543e358-8113-11e8-94bb-e9f8944a597d.png)
      - On Edit Blueprint page, in the Blueprint Components panel:
        ![image](https://user-images.githubusercontent.com/21063328/42389401-9b0c284a-8116-11e8-94e1-79d966967d60.png)
  - **Component details view**, components/ListView/ComponentDetailsView.js
    - This UI displays in two places:
      - On Blueprint page, click Selected Components tab, then click the name of a component in the list view. This will display the component details view.
      - On Edit Blueprint page, click any component name (in either Available Components or Blueprint Components panels) to display the details view.
    ![image](https://user-images.githubusercontent.com/21063328/42389438-ba047630-8116-11e8-9d0a-d78ce85d27ae.png)

**Comment by jkozol** [comment]
This has been implemented.
