### ISSUE TITLE
Country specific translations are broken

### ISSUE THREAD

**Issue by martinpitt** [osbuild/cockpit-composer#352]
We have some country specific translations like po/zh_CN.po. For most languages, a "language-only" translation like "de.po" is fine, but en, es, pt, and zh are exceptions. These *need* a country specific translations, as pt_BR vs. pt_PT, or zh_CN vs. zh_TW are wildly, or even *completely* different from another.

Right now, even after #351, if you select e. g. pt-BR or zh-CN in your browser, composer completely ignores these and appears in English.

**Comment by jkozol** [comment]
Country specific languages are supported if they are made available via weblate
