### ISSUE TITLE
Package selections are index-based

### ISSUE THREAD

**Issue by larskarlitski** [osbuild/cockpit-composer#378]
In several views that allow to select packages (with check boxes next to their names), the way the selection is kept seems to be index-based. This can lead to confusion. For example:

* selecting the first package and then filtering for other packages keeps the selection on the first package in the list, even if the package at the first position changed
* when selecting a package and removing it, the package that takes its place gets selected

I would expect that the selection is based on package names, so that the same packages keep being selected when the view changes. I think even clearing the selection when changing the list is preferable to the current situation.

I can see this in at least the "Selected Components" tab and the "Blueprint Components" in the "Edit Blueprint" view.

**Comment by jkozol** [comment]
I can not replicate this anymore.
