### ISSUE TITLE
Save recipe needs to save both version and release

### ISSUE THREAD

**Issue by jgiardino** [osbuild/cockpit-composer#49]
### Description of problem
Currently, the information that is provided on save is name and version, but release is not included. This means that the selected release version will not be saved with the recipe.

### Component (web, API, etc)
web

### Steps to Reproduce

1. Navigate to the Edit Recipe page
2. Find a component that has more than one version (click the component name, click the Version Release select menu to see number of available versions)
3. Click the component name to view details.
4. Click the Version Release select menu to select a different version and release value. (The default one is the one that displays in the popover when clicking the list item on the left, and is also most likely selected by default)
5. Save the recipe.
6. Reload the page.

### Actual results
The default values for version and release will display.

### Expected results
The selected values for version and release should display.

**Comment by jkozol** [comment]
This issue is outdated.
