### ISSUE TITLE
No arch info for packages

### ISSUE THREAD

**Issue by henrywang** [osbuild/cockpit-composer#648]
@jgiardino already added manage source feature. So the user is able to add source for different arch, like aarch64, ppc64, s390, etc. So we need a label in Available Component to notify user which package is for which arch. It's possible that user include packages from different arch in one blueprint. I don't know what will happen in lorax, but I can say the image will not work.

**Comment by jkozol** [comment]
Packages will only be loaded for the arch the user is building on. Currently we do not support cross arch support.
