### ISSUE TITLE
Adding a new source spent 2 hours in my local env.

### ISSUE THREAD

**Issue by henrywang** [osbuild/cockpit-composer#649]
I add a new source (https://dl.fedoraproject.org/pub/fedora/linux/development/rawhide/Server/aarch64/os/) in my local env. That spent 2 hours to get finished. I've encountered this issue twice.
At this scenario, the UI looks like stuck there. I don't know what happened and can I stop it? How can I stop it, by clicking cancel button? If I cancel it, can I add it again? Will it be duplicated?

Can we put it in async, and fire a callback to refresh Available Component and send notification when it the new source got added.

**Comment by jkozol** [comment]
Can no longer replicate.
