### ISSUE TITLE
Add support for repos.git

### ISSUE THREAD

**Issue by bcl** [osbuild/cockpit-composer#666]
### Description of problem
Add support for including files from a git repository. Documentation is here - https://weldr.io/lorax/lorax-composer.html#repos-git

rawhide currently supports this, and the f29 and f30 packages are currently in updates-testing.

**Comment by jkozol** [comment]
@bcl Is this still a desired feature?

**Comment by larskarlitski** [comment]
I don't think so. `osbuild-composer` does not currently support it. @teg Please correct me if I'm wrong.
