### ISSUE TITLE
Image building log shows "No log available" when building tar image

### ISSUE THREAD

**Issue by henrywang** [osbuild/cockpit-composer#733]
The log shows "No log available", and the log comes back when image building is "complete". lorax-composer API looks freeze during zx stage when I build tar image.
Tried tar, ext4, qcow2, and only tar image has this issue.

![Screenshot_2019-07-17 Image Builder - Pukaki](https://user-images.githubusercontent.com/672230/61382977-5b55c880-a8e0-11e9-9b39-edbcaf61f87b.png)

**Comment by KKoukiou** [comment]
I can't reproduce, I just tried it on my system, lorax-composer-30.19-1.fc30.x86_64, cockpit composer from master.
Is this deterministically reproduceable?

**Comment by jkozol** [comment]
We no longer support tar images.
