### ISSUE TITLE
Update error message on home page to include link to lorax-composer.service 

### ISSUE THREAD

**Issue by jgiardino** [osbuild/cockpit-composer#755]
When the following message displays, the error message provided by the api doesn't provide much information about why the error occurred. In the Web Console, the Services > lorax-composer.service page provides information that's useful for troubleshooting why the error occurred.

We should provide a link to this page. An example where this is currently implemented is here: https://github.com/weldr/cockpit-composer/blob/master/components/EmptyState/EmptyStateInactive.js#L130  

![image](https://user-images.githubusercontent.com/21063328/62470399-a73ab580-b79a-11e9-93eb-67e369c16120.png)

**Comment by jkozol** [comment]
Osbuild-composer and lorax-composer can be distinguished by the result of /api/status
