### ISSUE TITLE
upload image - embedded help for Azure images

### ISSUE THREAD

**Issue by jgiardino** [osbuild/cockpit-composer#781]
Help text should be provided in the image upload wizard steps to guide users in where to find the information we're asking.

Some notes:
- **The following help text is still WIP.** Edits are expected.
- One of the determining factors for whether text displays in a popover or inline is dependent on level of effort to implement popovers in the wizard. It's expected that the Esc key should close the popover, but in this case, we would not want Esc to close both the popover and the wizard. 😿 

**Help text to display when the user selects Azure**
TBD how this is presented (e.g. what screens, inline vs in popover)

> Image Builder can upload images you create to a Blob container in Microsoft Azure. When the image build is complete and the upload action is successful, the image file is available in the Storage account and Blob container that you specified.

**Field level help**
TBD how this is presented (E.g. helper text below the field vs in popover)

**subscription ID**
> You can find the Subscription ID on the **Subscriptions** page in the Azure portal.

**app (client) id, directory (tenant) id** (similar help text for both)
> You can find both the application (client) id and directory (tenant) id on the **Overview** page of an application.  You can find applications on the **App registrations** page in the Azure portal.

**secret**
> Provide a secret to authenticate with the application that you specified. You can create a secret on the **Certificates & secrets** page of an application. You can find applications on the **App registrations** page in the Azure portal.

**resource group**
> Provide the name of a resource group that includes the storage account you want to use. You can find resource groups on the **Resource groups** page in the Azure portal.

**storage account**
> Provide the name of a storage account that’s available in the resource group you specified. You can find storage accounts on the **Storage accounts** page in the Azure portal.

**Image name**
> Provide a file name to be used for the image file that will be uploaded.

NOTE that this string is defined by the user in the wizard, where as the other values should come from what already exists in Azure.

**Storage (blob) container**
> Provide the blob container to which the image file will be uploaded. You can find containers on the **Blobs** page of a storage account. You can find storage accounts on the **Storage accounts** page in the Azure portal.

**Comment by jgiardino** [comment]
Thanks for taking a look 👀 

Can you elaborate on the benefits of putting it there? I'm assuming this would make the help text available via the api to the UI, and also available in the CLI? If so, that would be nice. But would we be able to translate those strings if defined there?

Do you have a link to an example of the provider.toml file?

**Comment by jgiardino** [comment]
And now I see your comments in chat 😜 
Adding this link here for anyone else interested
https://github.com/bcl/lorax/blob/master-lifter/share/lifted/providers/azure/provider.toml

**Comment by larskarlitski** [comment]
> Should this kind of help information be part of the provider.toml file? We could add a 'help' field.

This has the same problem as having the names for output types in the API: they're not translatable. I think all strings should live in cockpit-composer, at least for now.

(Also, I'm not a fan of generated UIs :wink:)

**Comment by andreasn** [comment]
Could we link directly to the pages? Like the [Subscriptions page](https://portal.azure.com/#blade/Microsoft_Azure_Billing/SubscriptionsBlade) or the [Storage page](https://portal.azure.com/#blade/HubsExtension/BrowseResourceBlade/resourceType/Microsoft.Storage%2FStorageAccounts). Or are those URLs too unreliable?

**Comment by andreasn** [comment]
`Provide the ID of the Azure subscription to use. The subscription ID is provided in the list of subscriptions on the Subscriptions page in the Azure portal.`

I think the provide part is redundant here, since it's an input next to a label called _Subscription ID_.
What if we make _You_ the agent instead of the _Subscription ID_? I would also suggest cutting out the part with the list, since the page is pretty much just a list.
`You can find the Subscription ID on the Subscriptions page in the Azure Portal`

**Comment by bcl** [comment]
> If so, that would be nice. But would we be able to translate those strings if defined there?

Ah, good point. They need to be someplace with translation support.

**Comment by jgiardino** [comment]
Thanks for the reply, @bcl! For now, I'd suggest moving forward with keeping the strings in the UI so that we can translate them. 

Thanks for the feedback, @andreasn! I'd like to get some input from documentation on these strings as we discussed. In the current draft, all help text follows the same pattern where the first statement is an imperative statement that includes instruction about what type of value to provide. And the second statement is about where to find that information. 

I like your suggestion for the second statement better than what I originally drafted. 👍 

I agree that for some values, the imperative statement is redundant. I'm on the fence about whether to follow a consistent pattern for all strings even when redundant, or only provide the imperative statement when it provides some information that might otherwise not be obvious to the user. I could easily be convinced of the latter approach. I think my only reservation is that maybe the inconsistency could lead to confusion in some users 🤷‍♀ But that could easily be something we address later if it comes up during user testing. 

I also am on the fence about including URLs in this text for the reasons you mention. But I like the suggestion, and am curious how horrible of an experience would it be if a user encounters a broken link? Maybe that's a small risk for a decent benefit?

**Comment by jgiardino** [comment]
I updated the original description based on suggestions from @andreasn

**Comment by jgiardino** [comment]
Closed by #956
