### ISSUE TITLE
I18n of numbers and dates

### ISSUE THREAD

**Issue by jgiardino** [osbuild/cockpit-composer#898]
Formatting numbers such as "Install size 2,345 kB", this should use locale-aware formatting (decimal and thousands separator). This can be done with `number.toLocaleString(cockpit.language). Obviously this should be put into a wrapper in core/utils.js with a simple fallback when not running under Cockpit.

Any dates/times such as "Last modified date 01/12/17" should be formatted using moment.js, which deals with proper i18n (assuming one calls `moment.locale(cockpit.language)` initially) and also human-friendly relative timestamps like "a few moments ago" or "6 hours ago" where no perfect precision is wanted.

**Comment by jkozol** [comment]
Tracked by https://issues.redhat.com/browse/COMPOSER-1753
