### ISSUE TITLE
Please reduce size of log artifacts

### ISSUE THREAD

**Issue by martinpitt** [osbuild/cockpit-composer#912]
Our CI log server regularly runs out of disk space. I already cleaned up test results that are older than 10 days, but  it's still 30 GB. A lot of it is coming from cockpit-composer results like [this one](https://logs.cockpit-project.org/logs/pull-650-20200318-133453-540a6719-rhel-7-8-firefox-weldr-cockpit-composer-rhel-8/).

The wdio_report/ directory takes about 45 MB, of which 20 MB are *.jpeg screenshots and timeline-reporter.html is 26 MB. Neither compress very well, so that doesn't make much sense.

However, a good and simple start would be to only produce these artifacts if the test actually failed.  As a refinement, would it be possible to only produce screenshots for the failed tests, instead of all of them?

**Comment by jkozol** [comment]
@henrywang Since we have moved to using cockpit's testing framework has this issue been resolved?

**Comment by jkozol** [comment]
I am closing this because wdio_report is no longer used following the move to cockpit's testing framework.
