### ISSUE TITLE
Service "Start" button has two different status

### ISSUE THREAD

**Issue by henrywang** [osbuild/cockpit-composer#941]
How to reproduce:
1. osbuild-composer.socket is not started
2. Login with non-root user and do not select `Reuse my password for privileged tasks` checkbox.
3. The `Start` button has two different status, disabled and enabled.
![Screenshot_2020-04-25 Image Builder - localhost localdomain](https://user-images.githubusercontent.com/672230/80283076-b3f7a300-8747-11ea-9878-f09be86de830.png)
![Screenshot_2020-04-25 Image Builder - localhost localdomain(1)](https://user-images.githubusercontent.com/672230/80283079-b823c080-8747-11ea-818b-6864bec34a8a.png)

Sometimes looks like Pic 1 and sometimes like Pic 2.

Expected result:
The button should have a unique status

**Comment by jkozol** [comment]
@henrywang I am unable to replicate this. Are you still experiencing this issue?
