### ISSUE TITLE
Remove password verification

### ISSUE THREAD

**Issue by jgiardino** [osbuild/cockpit-composer#985]
### Description of problem
A [test in cockpit-composer](https://github.com/osbuild/cockpit-composer/blob/6e735255bb114be4ee5687d354aaec6fe3d67bd1/test/verify/check-custom#L173) regarding password verification is currently failing in Fedora but passing in RHEL. But considering the use cases that cockpit-composer supports, requiring an acceptable password based on the host machine isn't a valid use case. The proposed solution is to drop the password verification, to avoid blocking the user from defining the password that they want to use.

### Steps to Reproduce

1. Navigate to the Blueprint page.
2. Click the "Create User Account" button on the Customizations tab.
3. Specify a weak password, like "foobar", in both password fields.

### Actual results
A message displays, saying "Password quality check failed: The password is shorter than 8 characters" and you are prevented from creating the user account.

### Expected results
The user should not be blocked when specifying a weak password. Additionally, the password verification is checking the password policy on the host machine, which may or may not be the password policy of the target machine for the image you're building. Therefore, I'd propose we remove the password verification altogether, and just check that the passwords match.

cc @jkozol @henrywang

**Comment by jgiardino** [comment]
Including an example of the current password verification:
<img width="738" alt="image" src="https://user-images.githubusercontent.com/21063328/83692983-118ed300-a5c3-11ea-9a0c-32de6fc4e33c.png">

**Comment by snoopy72** [comment]
This request has not been solved, so i had to create a new ticket (#1079).
The solution in #986 is only for the display of the password strength.

**Comment by jgiardino** [comment]
Just restating what's noted in #1079, that the issue noted above belongs to https://github.com/cockpit-project/cockpit.
