### ISSUE TITLE
cached recipe doesn't work for recipe names with spaces 

### ISSUE THREAD

**Issue by jgiardino** [osbuild/cockpit-composer#99]
### Description of problem
RecipeAPI caches the recipe, so that if the same recipe contents are requested a second time, then the cached contents are used, instead of fetching them again. This does not appear to work for recipes that have spaces in the name, e.g. "Corporate Webserver" 

### Component (web, API, etc)
web

### How often reproducible
Always

### Steps to Reproduce

1. Navigate to the recipes page (list of recipes)
2. Click the kebab for a recipe and select Export
3. A modal opens and a spinner displays in place of the recipe contents while the contents are fetched. When the contents are available, they'll display in a text area.
4. Close the modal, then select Export for the same recipe.

### Actual results
If the recipe name has no spaces, then the contents are loaded immediately.
If the recipe name has spaces, then the spinner displays, indicating that the full fetch function is being executed, instead of just returning the cached recipe contents.

### Expected results
Cached recipe contents should be returned regardless of the recipe name format.

**Comment by jgiardino** [comment]
After adding redux to the project, this issue should be reviewed again. I still expect the same results as listed above, although this issue might no longer be specific to recipes with spaces in the name.

**Comment by jkozol** [comment]
Blueprint names can no longer contain spaces.
