### ISSUE TITLE
No rhel-edge-commit in RHEL-8-3

### ISSUE THREAD

**Issue by henrywang** [osbuild/cockpit-composer#997]
There's no "rhel-edge-commit" image type in UI in RHEL-8-3.
It should be backend issue. I got `Unknown compose type for architecture: rhel-edge-commit` error when I run `composer-cli compose start ostree rhel-edge-commit`

Install packages:
python3-osbuild-16-1.el8.noarch
osbuild-ostree-16-1.el8.noarch
osbuild-composer-worker-14-1.el8.x86_64
osbuild-16-1.el8.noarch
osbuild-composer-14-1.el8.x86_64

**Comment by larskarlitski** [comment]
This is still being worked on: https://github.com/osbuild/osbuild-composer/pull/740

**Comment by jkozol** [comment]
rhel-edge-commit is now included in rhel-8-3
